/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_itcast_uninstalllisten_MainActivity */

#ifndef _Included_com_itcast_uninstalllisten_MainActivity
#define _Included_com_itcast_uninstalllisten_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_itcast_uninstalllisten_MainActivity
 * Method:    unInstallListen
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_itcast_uninstalllisten_MainActivity_unInstallListen
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
